// program to check an Armstrong number of three digits-program11

let sum = 0;
const number = prompt('Enter a three-digit positive integer: ');
let temp = number;
while (temp > 0) {
    let remainder = temp % 10;
   sum += remainder * remainder * remainder;
 temp = parseInt(temp / 10); 
}
if (sum == number) {
    console.log(`${number} is an Armstrong number`);
}
else {
    console.log(`${number} is not an Armstrong number.`);
}

//multiplication table-program12
const number = parseInt(prompt('Enter an integer: '));
for(let i = 1; i <= 10; i++) {
const result = i * number;
console.log(`${number} * ${i} = ${result}`);
}

//program that checks if the number is positive, negative or zero-program13

const number = parseInt(prompt("Enter a number: "));
if (number > 0) {
    console.log("The number is positive");
}
else if (number == 0) {
  console.log("The number is zero");
}
else {
     console.log("The number is negative");
}

// program where the user has to guess a number generated by a program-program14

function guessNumber() {
const random = Math.floor(Math.random() * 10) + 1;
let number = parseInt(prompt('Guess a number from 1 to 10: '));
while(number !== random) {
        number = parseInt(prompt('Guess a number from 1 to 10: '));
    }
if(number == random) {
        console.log('You guessed the correct number.');
    }

  }
guessNumber();

// program to check if a key exists-program15

const person = {
    id: 01,
    name: 'bhavana',
    age: 23,
}
const niru = 'name' in person;
if(niru) {
    console.log('The key exists.');
}
else {
    console.log('The key does not exist.');
}
// program to display the date-program16
const date = new Date();
const n = date.toDateString();
const time = date.toLocaleTimeString();
console.log('Date: ' + n);
console.log('Time: ' + time);

//program to loop through an object using loop-program17

const student = { 
    name: 'John',
    age: 20,
    hobbies: ['reading', 'games', 'coding'],
};
for (let key in student) { 
    let value;
value = student[key];
console.log(key + " - " +  value); 
}

// js program to perform string-program18

const string1 = 'JavaScript Program';
const string2 = 'javascript program';
const result = string1.toUpperCase() === string2.toUpperCase();
if(result) {
    console.log('The strings are similar.');
} else {
    console.log('The strings are not similar.');
}
// taking kilometers input from the user-program19
const kilometers = prompt("Enter value in kilometers: ")
const factor = 0.621371
const miles = kilometers * factor
console.log(`${kilometers} kilometers is equal to ${miles} miles.`);

//// program to solve quadratic equation-program20
let root1, root2;
let a = prompt("Enter the first number: ");
let b = prompt("Enter the second number: ");
let c = prompt("Enter the third number: ");
let discriminant = (b * b - 4 * a * c);
if (discriminant > 0) {
    root1 = (-b + Math.sqrt(discriminant)) / (2 * a);
    root2 = (-b - Math.sqrt(discriminant)) / (2 * a);
    console.log(`The roots of quadratic equation are ${root1} and ${root2}`);
}
else if (discriminant == 0) {
    root1 = root2 = -b / (2 * a);
    console.log(`The roots of quadratic equation are ${root1} and ${root2}`);
}
else {
    let realPart = (-b / (2 * a)).toFixed(2);
    let imagPart = (Math.sqrt(-discriminant) / (2 * a)).toFixed(2);
    console.log(
    `The roots of quadratic equation are ${realPart} + ${imagPart}i and ${realPart} - ${imagPart}i`
  );
}


